#!/usr/bin/env python3
"""Generate the LaTeX table rows for the thesis BOM appendices.

Reads the production BOM exports and writes the row bodies that
``thesis/Backmatter/Appendix.tex`` pulls in with ``\\input``:

  * Appendix B (Bill of materials)  -> thesis/Backmatter/BOM_rows.tex
      per-board quantity + the LCSC unit price at the quantity needed to
      build 1000 boards (volume pricing), from the LCSC 1000-board
      quotation joined to the main BOM. The "JLCPCB Price" column in the
      main BOM CSV is wrong and is deliberately ignored.
  * Appendix C (Production cost detail) -> thesis/Backmatter/BOM_order_rows.tex
      actual JLCPCB assembly-order quantity, unit price (Total/Qty) and
      line cost, from the JLCPCB BOM-tool order export, joined to the main
      BOM on the LCSC part number.

The board design is frozen, so this normally only needs running once.
Re-run it if a production BOM changes. Requires ``xlrd`` and ``openpyxl``
(pip install xlrd openpyxl).

    python tools/gen_bom_appendix.py
"""
import csv
import io
import os
import xlrd
import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_BOM = os.path.join(ROOT, 'production', 'BOM_Board1_PCB1_2026-06-25.csv')
ORDER_BOM = os.path.join(ROOT, 'production', 'assembly-bom-order-2.xls')
VOLUME_BOM = os.path.join(ROOT, 'production', 'lcsc_bom_price_for_1000_boards.xls')
OUT_DIR = os.path.join(ROOT, 'thesis', 'Backmatter')
BUILD_QTY = 1000  # the LCSC quote prices the BOM at the quantities for this many boards


def esc(s):
    s = s.replace('\\', r'\textbackslash{}')
    for a, b in [('&', r'\&'), ('%', r'\%'), ('#', r'\#'),
                 ('_', r'\_'), ('$', r'\$'), ('{', r'\{'), ('}', r'\}')]:
        s = s.replace(a, b)
    s = s.replace('Ω', r'$\Omega$')  # ohm
    return s


def brk(s):  # let long unbroken part numbers wrap (not on '.', to keep decimals intact)
    s = esc(s)
    for ch in ['-', '/']:
        s = s.replace(ch, ch + r'\allowbreak{}')
    return s


def desig(s):  # space after comma so the cell wraps
    return esc(s).replace(',', ', ')


def descr(row):
    v = row['Value'].strip()
    c = row['Comment'].strip()
    return v if v else c


def read_main():
    """Main BOM is an irregular CSV: ', ' separators, padded quoted fields."""
    rows, by_sp = [], {}
    with open(MAIN_BOM, encoding='utf-8-sig') as f:
        rdr = csv.reader(f, skipinitialspace=True)
        header = [h.strip() for h in next(rdr)]
        for cells in rdr:
            if not cells or not any(c.strip() for c in cells):
                continue
            row = {header[i]: cells[i].strip() for i in range(len(header))}
            rows.append(row)
            sp = row['Supplier Part'].strip()
            if sp:
                by_sp[sp] = row
    return rows, by_sp


def read_order():
    """JLCPCB BOM-tool order export (xlsx content, .xls extension).

    Loaded via a BytesIO so openpyxl ignores the misleading extension.
    Header is on row index 4; the columns used are the matched JLCPCB
    part number (12), the order quantity (15), and the line total in USD (17).
    """
    wb = openpyxl.load_workbook(io.BytesIO(open(ORDER_BOM, 'rb').read()), data_only=True)
    ws = wb.worksheets[0]
    rows = [list(r) for r in ws.iter_rows(values_only=True)]
    asm = []
    for r in rows[5:]:
        if not r or r[0] in (None, ''):
            continue
        part = str(r[12]).strip() if r[12] else ''
        qty, total = r[15], r[17]
        if qty in (None, '') and total in (None, ''):
            continue
        asm.append(dict(part=part, qty=int(float(qty or 0)), ext=float(total or 0.0)))
    return asm


def read_volume():
    """LCSC quotation priced at the quantities needed for BUILD_QTY boards.

    Returns {lcsc#: unit_price_at_that_quantity}. The header is on row 4;
    columns: LCSC# (0), Quantity needed (7), Unit Price USD (13).
    """
    wb = xlrd.open_workbook(VOLUME_BOM)
    sh = wb.sheet_by_index(0)
    vol = {}
    for i in range(5, sh.nrows):
        v = sh.row_values(i)
        lcsc = str(v[0]).strip()
        if not lcsc:
            continue
        vol[lcsc] = float(v[13])
    return vol


def main():
    mrows, main_by_sp = read_main()
    asm = read_order()
    vol = read_volume()

    # Appendix B: per-board BOM rows, priced at BUILD_QTY-board volume.
    # The main-BOM "JLCPCB Price" column is wrong and is ignored; unit prices
    # come from the LCSC volume quote, joined on the LCSC part number.
    total = 0.0
    with open(os.path.join(OUT_DIR, 'BOM_rows.tex'), 'w', encoding='utf-8') as f:
        f.write('%% Auto-generated by tools/gen_bom_appendix.py. Unit prices are the LCSC price\n'
                '%% at the quantity needed for %d boards (production/lcsc_bom_price_for_1000_boards.xls);\n'
                '%% part details from production/BOM_Board1_PCB1_2026-06-25.csv. Do not edit by hand.\n'
                % BUILD_QTY)
        for row in mrows:
            q = int(row['Quantity'])
            mpn = row['Manufacturer Part'].strip()
            lcsc = row['Supplier Part'].strip()
            if lcsc and lcsc in vol:
                unit = vol[lcsc]
                ext = unit * q
                total += ext
                us, es = '%.4f' % unit, '%.4f' % ext
            else:
                us = es = '--'
            f.write('%d & %s & %s & %s & %s & %s & %s\\\\\n' % (
                q, brk(descr(row)) or '--', desig(row['Designator']),
                brk(mpn) if mpn else '--', esc(lcsc) if lcsc else '--', us, es))
    print('Appendix B per-board component cost at %d-board volume (USD): %.4f' % (BUILD_QTY, total))

    # Appendix C: order cost rows, sorted by descending line cost
    order_total = 0.0
    with open(os.path.join(OUT_DIR, 'BOM_order_rows.tex'), 'w', encoding='utf-8') as f:
        f.write('% Auto-generated by tools/gen_bom_appendix.py from '
                'production/assembly-bom-order-2.xls (JLCPCB order export) joined to the main BOM. Do not edit by hand.\n')
        for a in sorted(asm, key=lambda a: -a['ext']):
            m = main_by_sp.get(a['part'])
            d = desig(m['Designator']) if m else '--'
            v = brk(descr(m)) if m else '--'
            unit = a['ext'] / a['qty'] if a['qty'] else 0.0
            order_total += a['ext']
            f.write('%s & %s & %s & %d & %.4f & %.2f\\\\\n' % (
                v or '--', d, esc(a['part']), a['qty'], unit, a['ext']))
    print('Appendix C order component total (USD): %.2f' % order_total)


if __name__ == '__main__':
    main()
